CREATE TABLE IF NOT EXISTS "bulk_extract_runs" (
	"id" text PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"model_id" text NOT NULL,
	"status" text NOT NULL,
	"total_threads" integer DEFAULT 0 NOT NULL,
	"total_emails" integer DEFAULT 0 NOT NULL,
	"completed_threads" integer DEFAULT 0 NOT NULL,
	"completed_emails" integer DEFAULT 0 NOT NULL,
	"failed_threads" integer DEFAULT 0 NOT NULL,
	"current_thread_index" integer DEFAULT 0 NOT NULL,
	"current_thread_id" text,
	"current_thread_subject" text,
	"current_email_id" text,
	"current_email_label" text,
	"current_pass" integer,
	"current_email_index" integer,
	"current_email_total" integer,
	"total_cost_usd" text DEFAULT '0' NOT NULL,
	"started_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"finished_at" text,
	"last_error" text
);
