CREATE TABLE IF NOT EXISTS "docling_backfill_runs" (
	"id" text PRIMARY KEY NOT NULL,
	"status" text NOT NULL,
	"doc_limit" integer,
	"total_docs" integer DEFAULT 0 NOT NULL,
	"total_pages" integer DEFAULT 0 NOT NULL,
	"corpus_uncached_pages" integer DEFAULT 0 NOT NULL,
	"corpus_pending_docs" integer DEFAULT 0 NOT NULL,
	"completed_docs" integer DEFAULT 0 NOT NULL,
	"completed_pages" integer DEFAULT 0 NOT NULL,
	"failed_docs" integer DEFAULT 0 NOT NULL,
	"planned_hashes_json" text DEFAULT '[]' NOT NULL,
	"current_doc_index" integer DEFAULT 0 NOT NULL,
	"current_content_hash" text,
	"current_label" text,
	"current_pages_in_doc" integer,
	"stint_started_at" text,
	"completed_pages_at_stint_start" integer DEFAULT 0 NOT NULL,
	"active_elapsed_ms" integer DEFAULT 0 NOT NULL,
	"started_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"finished_at" text,
	"last_error" text
);
