export type ReferenceTopicExpectation = {
  key: string;
  title: string;
  parentSection: string;
  category: string;
  visibility: "PUBLIC" | "RESTRICTED";
  aliases: string[];
};

export type ReferenceMeetingExpectation = {
  meetingId: string;
  expectedMeetingRecords: string[];
  expectedTopics: ReferenceTopicExpectation[];
};

export const MAY_19_2026_EXPECTATION: ReferenceMeetingExpectation = {
  meetingId: "2026-05-19",
  expectedMeetingRecords: [
    "Meeting metadata",
    "Attendance and regrets",
    "Call to Order",
    "Date of Next Meeting",
    "Meeting Conclusion",
  ],
  expectedTopics: [
    {
      key: "kitchen-stack-presentation",
      title: "Kitchen Stack Cleaning Presentation",
      parentSection: "SPECIAL_PRESENTATIONS",
      category: "PRESENTATION",
      visibility: "PUBLIC",
      aliases: ["kitchen stack cleaning", "cleanouts", "cleaning schedule"],
    },
    {
      key: "trace-presentation",
      title: "Trace Consulting Group Presentation",
      parentSection: "SPECIAL_PRESENTATIONS",
      category: "PRESENTATION",
      visibility: "PUBLIC",
      aliases: ["trace consulting group", "bas system update", "enwave room overheating"],
    },
    {
      key: "previous-minutes",
      title: "March 23, 2026 Minutes Approved as Amended",
      parentSection: "APPROVAL_OF_PREVIOUS_MINUTES",
      category: "MOTION",
      visibility: "PUBLIC",
      aliases: ["approval of previous minutes", "march 23 2026 minutes", "approved as amended"],
    },
    {
      key: "financial-statements",
      title: "March 31, 2026 Unaudited Financial Statements and Variance Report",
      parentSection: "FINANCIAL_MATTERS",
      category: "INFORMATION",
      visibility: "PUBLIC",
      aliases: ["financial matters", "unaudited financial statements", "variance report"],
    },
    {
      key: "ratify-mua-vfd",
      title: "MUA No. 1 VFD Replacement",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["mua no 1 vfd replacement", "applied systems technologies", "variable frequency drive"],
    },
    {
      key: "ratify-pool-renewal",
      title: "Outdoor Pool Contract Renewal",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["outdoor pool contract renewal", "superior pool spa", "hot tub maintenance"],
    },
    {
      key: "ratify-marble-repair",
      title: "Lobby Marble Slabs Replacement",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["lobby marble slabs replacement", "absolute interior", "marble repair"],
    },
    {
      key: "ratify-elevator-tile",
      title: "Elevator Lobby Tile Sample",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["elevator lobby tile sample", "tile sample for the elevator lobby"],
    },
    {
      key: "ratify-column-tile",
      title: "Lobby Column Tile Sample",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["lobby column tile sample", "ground floor lobby column repairs"],
    },
    {
      key: "ratify-riser-assessment",
      title: "Riser Expansion Supports Condition Assessment",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["riser expansion supports condition assessment", "leading edge building engineers"],
    },
    {
      key: "ratify-window-cleaning",
      title: "Window Cleaning Contract",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["window cleaning contract", "northern touch", "window cleaning"],
    },
    {
      key: "ratify-budget",
      title: "2026-2027 Budget Documents",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["2026 2027 budget", "budget-related documents", "budget letter to residents"],
    },
    {
      key: "ratify-reserve-fund",
      title: "Reserve Fund Study Scenario 3",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["reserve fund study", "scenario 3", "funding recommendations"],
    },
    {
      key: "ratify-insurance-renewal",
      title: "Insurance Renewal",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["insurance renewal", "atrens-counsel", "annual premium"],
    },
    {
      key: "approve-kitchen-stack-cleaning",
      title: "Kitchen Stack Cleaning Approval",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "MOTION",
      visibility: "PUBLIC",
      aliases: ["kitchen stack cleaning", "new water plumbing", "35550"],
    },
    {
      key: "approve-holdback",
      title: "New Water Plumbing Holdback",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "MOTION",
      visibility: "PUBLIC",
      aliases: ["new water plumbing holdback", "partial release of holdback", "10572.61"],
    },
    {
      key: "electromagnetic-locking",
      title: "Electromagnetic Locking Device Installation",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["electromagnetic locking device installation", "put this item on the agenda"],
    },
    {
      key: "shared-facilities-rfs",
      title: "Shared Facilities Reserve Fund Study",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["shared facilities reserve fund study", "egis", "refund or redo"],
    },
    {
      key: "approve-bas-system",
      title: "BAS System Approval",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "MOTION",
      visibility: "PUBLIC",
      aliases: ["bas system", "trace consulting group", "5100", "7500"],
    },
    {
      key: "heat-exchanger",
      title: "Heat Exchanger",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "DEFERRED",
      visibility: "PUBLIC",
      aliases: ["heat exchanger", "plate pack", "83 gaskets"],
    },
    {
      key: "gic-investments",
      title: "GIC Investments",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["gic investments", "rate sheet", "investment advisor"],
    },
    {
      key: "suite-door-lock-repairs",
      title: "Suite Door Lock Repairs",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "INFORMATION",
      visibility: "PUBLIC",
      aliases: ["suite door lock repairs"],
    },
    {
      key: "minute-taker",
      title: "Minute Taker",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["minute taker", "solicitor's opinion"],
    },
    {
      key: "retention-tank-cover",
      title: "Retention Tank Cover Replacement",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "INFORMATION",
      visibility: "PUBLIC",
      aliases: ["retention tank cover replacement", "continue to be monitored"],
    },
    {
      key: "suite-2702-legal-letter",
      title: "Suite 2702 Legal Letter",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "MOTION",
      visibility: "RESTRICTED",
      aliases: ["suite 2702 legal letter", "legal letter to the owner of suite 2702"],
    },
    {
      key: "suite-817-window",
      title: "Suite 817 Broken Window Glass",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "MOTION",
      visibility: "RESTRICTED",
      aliases: ["suite 817 broken window glass", "hi-lon glass", "265.55"],
    },
    {
      key: "suite-2005-water-meter",
      title: "Suite 2005 Water Meter Leak",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "RESTRICTED",
      aliases: ["suite 2005 water meter leak", "legal action", "follow-up letter"],
    },
    {
      key: "work-completed",
      title: "Work Completed List",
      parentSection: "WORK_COMPLETED",
      category: "INFORMATION",
      visibility: "PUBLIC",
      aliases: ["work completed", "completed items"],
    },
    {
      key: "elevator-room",
      title: "Elevator Room",
      parentSection: "NEW_OTHER_BUSINESS",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["elevator room", "hoist ropes", "circulate information"],
    },
    {
      key: "dishwasher-supply-line",
      title: "Dishwasher Supply Line",
      parentSection: "NEW_OTHER_BUSINESS",
      category: "INFORMATION",
      visibility: "PUBLIC",
      aliases: ["dishwasher supply line", "additional quotations are currently pending"],
    },
    {
      key: "request-for-records",
      title: "Request for Records",
      parentSection: "NEW_OTHER_BUSINESS",
      category: "INFORMATION",
      visibility: "RESTRICTED",
      aliases: ["request for records", "records were provided to the owner", "redact records"],
    },
  ],
};

export const JUNE_30_2026_EXPECTATION: ReferenceMeetingExpectation = {
  meetingId: "2026-06-30",
  expectedMeetingRecords: [
    "Meeting metadata",
    "Attendance and regrets",
    "Call to Order",
    "Date of Next Meeting",
    "Meeting Conclusion",
  ],
  expectedTopics: [
    {
      key: "previous-minutes",
      title: "May 19, 2026 Minutes Approved as Amended",
      parentSection: "APPROVAL_OF_PREVIOUS_MINUTES",
      category: "MOTION",
      visibility: "PUBLIC",
      aliases: ["approval of previous minutes", "may 19 2026 minutes", "approved as amended"],
    },
    {
      key: "financial-housekeeping",
      title: "Housekeeping and Superintendent Variances",
      parentSection: "FINANCIAL_MATTERS",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["housekeeping and superintendent", "account 6210", "account 6248"],
    },
    {
      key: "financial-building-repairs",
      title: "Building Repairs and Maintenance Variances",
      parentSection: "FINANCIAL_MATTERS",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["building repairs and maintenance", "account 6610", "tractor repair expenses"],
    },
    {
      key: "ratify-gic",
      title: "GIC Investment",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "PUBLIC",
      aliases: ["gic investment", "versa bank", "home trust", "scotia wealth management"],
    },
    {
      key: "ratify-unit-610-records",
      title: "Unit 610 Request for Records",
      parentSection: "MANAGEMENT_REPORT_RATIFICATION",
      category: "RATIFICATION",
      visibility: "RESTRICTED",
      aliases: ["unit 610", "request for records", "records were released electronically"],
    },
    {
      key: "steam-room-heat-pump",
      title: "Steam Room Heat Pump",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "MOTION",
      visibility: "PUBLIC",
      aliases: ["steam room heat pump", "heat pump design project", "trace consulting group"],
    },
    {
      key: "steam-equipment-maintenance",
      title: "One-Year Steam Equipment Preventative Maintenance Agreement",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["one-year steam equipment preventative maintenance agreement", "enwave energy services"],
    },
    {
      key: "hoist-rope-corrosion",
      title: "Premature Hoist Rope Corrosion",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "MOTION",
      visibility: "PUBLIC",
      aliases: ["premature hoist rope corrosion", "elevator governor ropes", "engineering investigation"],
    },
    {
      key: "stairwell-f-cleaning",
      title: "Cleaning of Stairwell F",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["cleaning of stairwell f", "omega superior maintenance", "maglock installation"],
    },
    {
      key: "riser-expansion-support",
      title: "Riser Expansion and Support System",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "MOTION",
      visibility: "PUBLIC",
      aliases: ["riser expansion and support system", "phase 1", "three risers only"],
    },
    {
      key: "shared-reserve-fund-study",
      title: "Shared Reserve Fund Study",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["shared reserve fund study", "egis", "seek reimbursement from egis"],
    },
    {
      key: "toilet-laundry-supply-lines",
      title: "Replacement of Toilet and Laundry Supply Lines",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["replacement of toilet and laundry supply lines", "new water plumbing", "resident interest survey"],
    },
    {
      key: "pump-12a-replacement",
      title: "Pump 12A Replacement",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "MOTION",
      visibility: "PUBLIC",
      aliases: ["pump 12a replacement", "applied systems technologies", "domestic hot water pump p12a"],
    },
    {
      key: "booster-pump-replacement",
      title: "Booster Pump Replacement",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["booster pump replacement", "domestic booster pump duplex system"],
    },
    {
      key: "agm",
      title: "Annual General Meeting (AGM)",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "INFORMATION",
      visibility: "PUBLIC",
      aliases: ["annual general meeting", "agm", "october 20 2026"],
    },
    {
      key: "ai-minutes",
      title: "AI-Assisted Preparation for Board Meeting Minutes",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "INFORMATION",
      visibility: "PUBLIC",
      aliases: ["ai-assisted preparation for board meeting minutes", "legal opinion has been obtained"],
    },
    {
      key: "corporation-records",
      title: "Corporation Records",
      parentSection: "NEW_OTHER_BUSINESS",
      category: "ACTION_ONLY",
      visibility: "PUBLIC",
      aliases: ["corporation records", "currently in storage"],
    },
    {
      key: "staffing-update",
      title: "Property Management Staffing Update",
      parentSection: "NEW_OTHER_BUSINESS",
      category: "INFORMATION",
      visibility: "PUBLIC",
      aliases: ["property management staffing update", "haidar mukadam", "promoted to property manager"],
    },
    {
      key: "unit-2005-chargeback",
      title: "Unit 2005 Chargeback Dispute",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "RESTRICTED",
      aliases: ["unit 2005 chargeback dispute", "pre-lien and lien"],
    },
    {
      key: "resident-slip-fall",
      title: "Resident Slip and Fall Incident",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "INFORMATION",
      visibility: "RESTRICTED",
      aliases: ["resident slip and fall incident", "no update has been received"],
    },
    {
      key: "noise-investigation",
      title: "Noise Investigation, Unit 210 and Unit 211",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "ACTION_ONLY",
      visibility: "RESTRICTED",
      aliases: ["noise investigation", "unit 210", "unit 211", "heat pump loop turbulence"],
    },
    {
      key: "unit-712-leak",
      title: "Unit 712 Leak Chargeback and Outstanding Account Balance",
      parentSection: "MANAGEMENT_REPORT_DISCUSSION_APPROVAL",
      category: "INFORMATION",
      visibility: "RESTRICTED",
      aliases: ["unit 712 leak chargeback", "outstanding account balance"],
    },
  ],
};

export function getReferenceExpectation(
  meetingId: string,
): ReferenceMeetingExpectation | null {
  if (meetingId === MAY_19_2026_EXPECTATION.meetingId) {
    return MAY_19_2026_EXPECTATION;
  }
  if (meetingId === JUNE_30_2026_EXPECTATION.meetingId) {
    return JUNE_30_2026_EXPECTATION;
  }
  return null;
}
